apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
  namespace: ems-testing
  labels:
    app: identity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        app: identity
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: identity
        image: identity:latest
        imagePullPolicy: Never  
        ports:
        - containerPort: 9002
        env:
        - name: ELASTICSEARCH_URL
          value: http://172.31.11.243:9201
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://192.168.1.163:3306/invoice
        volumeMounts:
        - name: image-volume
          mountPath: /home/ubuntu/ems_testing_imag_bkp
      volumes:
      - name: image-volume
        persistentVolumeClaim:
          claimName: pvc
