apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: ems-testing
spec:
  selector:
    app: employee
  ports:
  - protocol: TCP
    port: 8012         # External port to expose
    targetPort: 8012  # Internal container port
  type: LoadBalancer   # Change from NodePort to LoadBalancer
  externalIPs:
  - 172.31.11.243

