apiVersion: v1
kind: Service
metadata:
  name: identity-service
  namespace: ems-testing
spec:
  selector:
    app: identity
  ports:
  - protocol: TCP
    port: 9002         # External port to expose
    targetPort: 9002  # Internal container port
  type: LoadBalancer   # Change from NodePort to LoadBalancer
  externalIPs:
  - 172.31.11.243

