apiVersion: v1
kind: Service
metadata:
  name: invoice-service
  namespace: ems-testing
spec:
  selector:
    app: invoice
  ports:
  - protocol: TCP
    port: 8002         # External port to expose
    targetPort: 8002   # Internal container port
  type: LoadBalancer   # Change from NodePort to LoadBalancer
  externalIPs:
  - 172.31.11.243

