apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: ems-testing
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 2801
    targetPort: 2801
  type: LoadBalancer
  externalIPs:
  - 172.31.11.243

